from __future__ import annotations

import re
from typing import Any

from aeios.agents.base import BaseAgent
from aeios.core.types import Task, TaskStatus

_URL_RE = re.compile(r"https?://[^\s<>\"']+", re.IGNORECASE)
_BACKTICK_PATH_RE = re.compile(r"`([A-Za-z0-9_./\\-]+\.[A-Za-z0-9]+)`")
_ACTION_PATH_RE = re.compile(
    r"(?:(?:create|write|edit|update|implement|save|add|scaffold)\s+"
    r"(?:(?:a|an|the|file|to|into|in)\s+)*)"
    r"([A-Za-z0-9_./\\-]+\.[A-Za-z0-9]+)",
    re.IGNORECASE,
)
_IMPL_HINTS = (
    "implement",
    "create",
    "write",
    "edit",
    "update",
    "scaffold",
    "generate",
    "add file",
    "save ",
    "patch",
)


def _extract_url(goal: str) -> str | None:
    match = _URL_RE.search(goal)
    return match.group(0).rstrip(".,);]") if match else None


def _extract_target_path(goal: str) -> str | None:
    tick = _BACKTICK_PATH_RE.search(goal)
    if tick:
        return tick.group(1).replace("\\", "/")
    action = _ACTION_PATH_RE.search(goal)
    if action:
        return action.group(1).replace("\\", "/")
    return None


def _wants_implementation(goal: str) -> bool:
    goal_l = goal.lower()
    return any(k in goal_l for k in _IMPL_HINTS)


def _stub_content(path: str, goal: str) -> str:
    name = path.replace("\\", "/").rsplit("/", 1)[-1]
    if name.endswith(".py"):
        module = name[:-3]
        return (
            f'"""Generated by AEIOS SoftwareEngineer for: {goal.strip()}"""\n\n'
            f"def main() -> None:\n"
            f'    print("{module}: stub ready")\n\n'
            f'if __name__ == "__main__":\n'
            f"    main()\n"
        )
    if name.endswith((".md", ".txt", ".rst")):
        return f"# {name}\n\nGoal: {goal.strip()}\n\n## Notes\n\n- Stub written by AEIOS SoftwareEngineer.\n"
    if name.endswith((".yml", ".yaml")):
        return f"# Generated by AEIOS for: {goal.strip()}\nname: stub\n"
    if name.endswith(".json"):
        return '{\n  "generated_by": "aeios",\n  "status": "stub"\n}\n'
    return f"# Generated by AEIOS SoftwareEngineer\n# Goal: {goal.strip()}\n"


def _step(
    name: str,
    *,
    status: str,
    output: Any = None,
    error: str | None = None,
    observation: str | None = None,
    **extra: Any,
) -> dict[str, Any]:
    row: dict[str, Any] = {"step": name, "status": status, "output": output, "error": error}
    if observation:
        row["observation"] = observation
    row.update(extra)
    return row


class SoftwareEngineerAgent(BaseAgent):
    name = "software_engineer"
    role = "software_engineer"

    def execute(self, task: Task) -> Task:
        task.status = TaskStatus.RUNNING
        # Plan
        task.plan = self.plan(task.goal)
        task.touch()

        observations: list[str] = []
        goal_l = task.goal.lower()

        # Act → observe: workspace listing
        listing = self.call_tool("filesystem", action="list", path=".")
        list_obs = None
        if listing.ok:
            entries = listing.output if isinstance(listing.output, list) else [listing.output]
            list_obs = f"workspace: {len(entries)} entries"
            observations.append(list_obs)
        else:
            list_obs = f"list failed: {listing.error}"
            observations.append(list_obs)
        task.steps.append(
            _step(
                "list_workspace",
                status="ok" if listing.ok else "error",
                output=listing.output,
                error=listing.error,
                observation=list_obs,
            )
        )

        if task.goal.strip().lower() in {"hello", "hi", "ping"}:
            echo = self.call_tool("echo", message="AEIOS kernel online.")
            obs = str(echo.output) if echo.ok else f"echo failed: {echo.error}"
            task.steps.append(
                _step(
                    "hello",
                    status="ok" if echo.ok else "error",
                    output=echo.output,
                    error=echo.error,
                    observation=obs,
                )
            )
            task.status = TaskStatus.COMPLETED if echo.ok else TaskStatus.FAILED
            task.result = str(echo.output) if echo.ok else None
            task.error = echo.error
            task.touch()
            return task

        # Act → observe: sandboxed shell when goal implies it
        if "shell" in self.kernel.tools and any(
            k in goal_l for k in ("shell", "pwd", "ls ", "command")
        ):
            shell = self.call_tool("shell", command="pwd")
            if shell.ok and isinstance(shell.output, dict):
                cwd = (shell.output.get("stdout") or "").strip()
                obs = f"cwd: {cwd}"
                observations.append(obs)
            else:
                obs = f"shell error: {shell.error}"
                observations.append(obs)
            task.steps.append(
                _step(
                    "shell_pwd",
                    status="ok" if shell.ok else "error",
                    output=shell.output,
                    error=shell.error,
                    observation=obs,
                )
            )

        # Act → observe: HTTP fetch when URL or fetch/http keywords present
        url = _extract_url(task.goal)
        wants_http = url is not None or any(
            k in goal_l for k in ("http", "fetch", "download", "api endpoint")
        )
        if wants_http and "http" in self.kernel.tools and url:
            http = self.call_tool("http", method="GET", url=url)
            body_preview = ""
            if isinstance(http.output, dict):
                body = str(http.output.get("body") or "")
                body_preview = body[:400]
            if http.ok and isinstance(http.output, dict):
                obs = (
                    f"http {http.output.get('status_code')} from {url} "
                    f"({http.output.get('bytes', 0)} bytes)"
                )
                observations.append(obs)
            else:
                obs = f"http error for {url}: {http.error}"
                observations.append(obs)
            task.steps.append(
                _step(
                    "http_fetch",
                    status="ok" if http.ok else "error",
                    url=url,
                    output=(
                        {
                            "status_code": http.output.get("status_code")
                            if isinstance(http.output, dict)
                            else None,
                            "truncated": http.output.get("truncated")
                            if isinstance(http.output, dict)
                            else None,
                            "body_preview": body_preview,
                        }
                        if http.output
                        else None
                    ),
                    error=http.error,
                    observation=obs,
                )
            )

        # Lightweight read when goal names a workspace file that exists
        if listing.ok and isinstance(listing.output, list):
            self._maybe_read_named_file(task, listing.output, observations)

        # Act → observe: write/update when goal implies implementation
        if _wants_implementation(task.goal):
            self._maybe_write_or_update(task, observations)

        task.status = TaskStatus.COMPLETED
        obs_block = "; ".join(observations) if observations else "none"
        task.result = (
            f"Accepted goal: {task.goal}\n"
            f"Plan: {' → '.join(task.plan)}\n"
            f"Observations: {obs_block}\n"
            f"Workspace entries: {listing.output if listing.ok else 'unavailable'}"
        )
        task.touch()
        return task

    def _maybe_read_named_file(
        self,
        task: Task,
        entries: list[str],
        observations: list[str],
    ) -> bool:
        """If the goal mentions a top-level file, read it (observe)."""
        goal_l = task.goal.lower()
        for name in entries:
            if not name or name.startswith("."):
                continue
            if name.lower() in goal_l and ("." in name or name.lower() in {"readme", "makefile"}):
                read = self.call_tool("filesystem", action="read", path=name)
                if read.ok:
                    text = str(read.output)
                    obs = f"read {name} ({len(text)} chars)"
                    observations.append(obs)
                    out: Any = text[:500]
                else:
                    obs = f"read {name} failed: {read.error}"
                    observations.append(obs)
                    out = None
                task.steps.append(
                    _step(
                        "read_file",
                        status="ok" if read.ok else "error",
                        path=name,
                        output=out,
                        error=read.error,
                        observation=obs,
                    )
                )
                return True
        return False

    def _maybe_write_or_update(self, task: Task, observations: list[str]) -> None:
        """Create or edit a file in the workspace jail when the goal implies it."""
        path = _extract_target_path(task.goal) or "IMPLEMENTATION.md"
        goal_l = task.goal.lower()
        existing = self.call_tool("filesystem", action="read", path=path)
        content = _stub_content(path, task.goal)

        if existing.ok and any(k in goal_l for k in ("edit", "update", "patch", "append")):
            # Prefer append when goal says append; otherwise replace with a short edit marker.
            if "append" in goal_l:
                mode = "append"
                content = f"\n\n## Update\n\n{task.goal.strip()}\n"
            else:
                mode = "replace"
                prior = str(existing.output)
                content = (
                    prior.rstrip()
                    + f"\n\n<!-- AEIOS update: {task.goal.strip()} -->\n"
                )
            result = self.call_tool(
                "filesystem",
                action="update",
                path=path,
                content=content,
                mode=mode,
            )
            step_name = "update_file"
        else:
            result = self.call_tool(
                "filesystem",
                action="write",
                path=path,
                content=content,
            )
            step_name = "write_file"

        if result.ok and isinstance(result.output, dict):
            nbytes = result.output.get("bytes", 0)
            rel = result.output.get("path", path)
            obs = f"{step_name.replace('_', ' ')} {rel} ({nbytes} bytes)"
            observations.append(obs)
            out = result.output
        elif result.ok:
            obs = f"{step_name.replace('_', ' ')} {path}"
            observations.append(obs)
            out = result.output
        else:
            obs = f"{step_name} failed for {path}: {result.error}"
            observations.append(obs)
            out = None

        task.steps.append(
            _step(
                step_name,
                status="ok" if result.ok else "error",
                path=path,
                output=out,
                error=result.error,
                observation=obs,
            )
        )
